---
- name: Read Attributes for CSV Files
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read csv file from tmp
      community.general.read_csv:
        path: poc-test.csv
        fieldnames: name,user,app1,app2
        delimiter: ';'
      register: server
      delegate_to: localhost
    - ansible.builtin.debug:
        msg: 'Server name: {{ server.list.1.name }} for application user {{ server.list.1.user }} with application {{ server.list.1.app1 }} , {{ server.list.1.app2 }}'
